# Site settings
title: FinPics
email: rgfindley@bluefinengineering.com
description: > # this means to ignore newlines until "baseurl:"
  The life and times of Randy Findley & friends from 1999 to 2009.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://finpics.com" # the base hostname & protocol for your site
twitter_username: rgfindl
github_username:  rgfindl

# Build settings
markdown: kramdown

# Gems
gems:
  - jekyll-gallery-generator

gallery:
  # path to the gallery
  dir: photos
  # title for gallery index
  title: "Photos"
  # title prefix for gallery page. title=title_prefix+gallery_name
  title_prefix: "Photos: "
  # field to control sorting of galleries for the index page
  # (possible values are: title, date_time, best_image)
  sort_field: "title"
  # sizes for thumbnails
  thumbnail_size:
    x: 400
    y: 400